[workspace]
resolver = "2"
members = ["models/starwars", "tide/starwars"]

[workspace.package]
version = "7.0.0"
edition = "2021"

[workspace.dependencies]
async-graphql = "7.0"
async-graphql-tide = "7.0"
